spring:
  application:
    name: konfi
  datasource:
    datas
  data:
    mongodb:
      host: localhost
      port: 27017
      database: default
      username: root
      password: password
      authentication-database: admin
      auto-index-creation: true