spring:
  application:
    name: konfi
  data:
    mongodb:
      host: localhost
      port: 27017
      database: default
      username: root
      password: password
      authentication-database: admin
      auto-index-creation: true
logging:
  level:
    root: debug

konfi:
  auth:
    jwt:
      secret: ${KONFI_AUTH_JWT_SECRET:pleasechangemeassoonaspossible}
      algorithm: ${KONFI_AUTH_JWT_ALGORITHM:RSA256}
      access-token-validity-duration: 24h